### ISSUE TITLE
frozen::string vs string_view?

### ISSUE THREAD

**Issue by henris42** [serge-sans-paille/frozen#102]
Hi,

Have you considered compatibility between frozen::string and c++17 std::string_view?

I started wondering if frozen:string could be inherited from string_view, and thus have all the functionality & compability there.
The rationale is that I'm developing embedded stuff, and often I try to leverage string_view instead on normal strings. It would be cool if frozen could be trivially compatible with this, so that ie interface API:s would be written with string_view, but use frozen::string in the implementation.

Thoughts?

**Comment by serge-sans-paille** [comment]
If I understand correctly, that's exactly what's proposed in https://github.com/serge-sans-paille/frozen/pull/92
