### ISSUE TITLE
frozen::unordered_map, fails in MSVC 2017 with C++17

### ISSUE THREAD

**Issue by malium** [serge-sans-paille/frozen#108]
I'm trying to create a constexpr unordered_map, with constexpr information:
`static constexpr frozen::unordered_map<Uuid, sizet, gpr::ENGINE_MANAGERS, frozen::elsa<Uuid>, std::equal_to<Uuid>>
gManagerMap = { std::make_pair(gpr::Engine::ManagerUuid, 0Ull) };`
Where, the class Uuid is completely constexpr (constructor, copy, move, equal/inequal), I've made an specification of elsa<Uuid> and that alone returns the hash value correctly at compile time. gpr::ENGINE_MANAGERS is also a constexpr variable which right now is just 1.
gpr::Engine::ManagerUuid is also a constexpr variable, so I don't know where am I failing or it's an implementation fault. MSVC says that I'm trying to modify a constant storage.
I've tried with the make_unordered_map and without using std::make_pair, I don't know what else to do,
Thank you.

**Comment by garbageslam** [comment]
It might help if you can produce an MCVE, we should be able to repro with one of the online compilers?

**Comment by malium** [comment]
I attach you a pastebin link where the code is, I hope you can see where I'm wrong or if we can solve an issue.[https://pastebin.com/N5yit3mr](url)

**Comment by malium** [comment]
My fault, had a problem with the header inclusion in MSVC, it was including different versions of the c++ standard and there was a mismatch in the definition of std::pair. Also I have to learn more about constexpr and it's storage duration.
