### ISSUE TITLE
Support for std::array?

### ISSUE THREAD

**Issue by 0x8000-0000** [serge-sans-paille/frozen#119]
Is it possible to have a unordered_map constructor and make_unordered_map that take a constexpr std::array<std::pair<T, U>> as argument?

**Comment by serge-sans-paille** [comment]
Can you confirm #120 fixes your issue?

**Comment by 0x8000-0000** [comment]
> 
> 
> Can you confirm #120 fixes your issue?

Yes, it works great, thank you!
