### ISSUE TITLE
Warning concerning a missing constexpr

### ISSUE THREAD

**Issue by tetsuhaut** [serge-sans-paille/frozen#122]
In file include/frozen/random.h, line 55,
~~~
if(modulus != 0)
~~~
should read
~~~
if constexpr (modulus != 0)
~~~
I tried to make a pull request but couldn't due to a 403 error.

**Comment by serge-sans-paille** [comment]
frozen is written in c++14 where `if constexpr` is not supported. I'll use another approach.

**Comment by serge-sans-paille** [comment]
CAn you confirm #128 fixes your issue? Thanks!

**Comment by tetsuhaut** [comment]
Works great :)
