### ISSUE TITLE
CMake Support

### ISSUE THREAD

**Issue by colin-daniels** [serge-sans-paille/frozen#16]
What's your opinion on adding support for the CMake build system? I think it's popular enough to be worthwhile to include but the issue is finding a way to not have to update a list of sources in two places to maintain both GNU Make and CMake.

The major advantage is being able to add it to another CMake project extremely easily, e.g.
```cmake
project(foo CXX)

# ...

# manually download or use something like https://github.com/Crascit/DownloadProject to pull from github
add_subdirectory(frozen)
target_link_libraries(foo PRIVATE frozen)
```
and have it deal with the include directories, any future compile definitions, etc automatically.

**Comment by serge-sans-paille** [comment]
frozen is header-only, so using frozen in another CMake project boilds down to

```
project(foo CXX)

# manually download or use something like https://github.com/Crascit/DownloadProject to pull from github
include(frozen/include)
# that's it
```

I don't see what you may want to add to this setup?

**Comment by colin-daniels** [comment]
True enough, the base functionality work fine at the moment. The other advantages are just tying in the tests with CMake (so that if someone uses your library with CMake can run your tests along with theirs with no extra code), and allowing for easier integration if you end up using things like particular compile definitions (e.g. to switch on/off specific behavior).

Given the difficulties with maintaining two separate (?) lists of sources for the test code (unless a glob/pattern match is used to just add all the files in the test directory), it's up to you. I've already made the modifications on my fork so obviously feel free to do as you see fit.

**Comment by serge-sans-paille** [comment]
@colin-daniels I glanced at your fork, if you issue a PR that removes the cmake-based tests and adds your Cmakefile, i'll gladly review and integrate it :-)

**Comment by apmccartney** [comment]
I think this issue has been resolved. =)

**Comment by serge-sans-paille** [comment]
yep :-)
