### ISSUE TITLE
Sequencing in make_unordered_array.

### ISSUE THREAD

**Issue by colin-daniels** [serge-sans-paille/frozen#17]
Relatively pedantic, but the code for `make_unordered_array` in algorithms.h notes that order isn't guaranteed by the standard (see below).

```c++
template <class T, std::size_t N, class Iter, std::size_t... I>
constexpr std::array<T, N> make_unordered_array(Iter &iter,
                                                std::index_sequence<I...>) {
  // the order is not guaranteed by the standard,
  // *BUT* we don't care as we sort it later
  return {{((void)I, *iter++)...}};
}
```
Where actually it is, in §8.5.4 of the C++14 (draft) standard.

> Within the _initializer-list_ of a _braced-init-list_, the _initializer-clauses_, including any that result from pack expansions (14.5.3), are evaluated in the order in which they appear. That is, every value computation and side effect associated with a given _initializer-clause_ is sequenced before every value computation and side effect associated with any _initializer-clause_ that follows it in the comma-separated list of the _initializer-list_.

(Ok, I admit I thought it was undefined behavior at first, fixed it, and then realized I was wrong)

**Comment by serge-sans-paille** [comment]
Fixed in master, thanks!
