### ISSUE TITLE
Which version should I use?

### ISSUE THREAD

**Issue by jaskij** [serge-sans-paille/frozen#171]
For stable experience, which version of frozen should I use? Normally, I pick the latest GH release/git tag, but the most recent one for frozen is from 2022, so it seems you are not adding those regularly. Should I just use the `master` branch?

It would be good to add this information to the README. There is a lot of information on how to get started using frozen, but not which version should be used.

**Comment by serge-sans-paille** [comment]
yeah, I'd use the master branch
