### ISSUE TITLE
Release a new version (tag)

### ISSUE THREAD

**Issue by anders-wind** [serge-sans-paille/frozen#176]
The version on vcpkg still points to v1.1.1, I would like to update the port, but it would be nice if I could point to a release tag instead of a commit hash. 

Is it possible for you to create a new release tag?

**Comment by dmitrmax** [comment]
Agreed! More than two years since last release. Since then a lot of fixes for different new compilers were merged into master.

**Comment by serge-sans-paille** [comment]
https://github.com/serge-sans-paille/frozen/tree/1.2.0

**Comment by anders-wind** [comment]
Amazing! Thanks a lot, I created a PR in vcpkg to get it upgraded there: https://github.com/microsoft/vcpkg/pull/40755
