### ISSUE TITLE
carray/cvector as first-class citizen

### ISSUE THREAD

**Issue by jaydee-io** [serge-sans-paille/frozen#34]
Maybe `frozen::bits::carray` and `frozen::bits::cvector` could be moved to top level `frozen::array` and `frozen::vector`. Like the `*map` and `*set`.

This would allow `frozen` users to use theses full `constexpr` versions of `std::array` and `std::vector` in their own code.

What do you think ?

**Comment by serge-sans-paille** [comment]
They don't fit in the category of « require some pre-computation that is hidden by the constexpr keyword » category, so i'd rather keep then in ``bits/``

**Comment by 0x8000-0000** [comment]
@serge-sans-paille  - thank you for the answer. We're looking to implement a "map of string to ordered vector of strings". It would seem carray/vector would be a good solution as the "value type" in the frozen::unordered_map . If those types are not part of the public interface, what alternative implementation do you suggest?

**Comment by serge-sans-paille** [comment]
ordered vector of string is somehow similar to a `frozen::set<frozen::string>`, but without uniqueness. It's also similar to `std::array<frozen::string>` but then you get a fixed size. I understand why you would like to use a `frozen::bits::carray`. For these :-/
