### ISSUE TITLE
Usecase

### ISSUE THREAD

**Issue by dkrikun** [serge-sans-paille/frozen#6]
Could you please explain why one want to have a datastructure that could not be updated?

**Comment by serge-sans-paille** [comment]
A typical use case is when parsing text, you have a predefined set of keywords and you want to check if a user string is a keyword, then you can do

```
constexpr frozen::unordered_set<frozen::string, 4> Keywords = { "keyword0", "keyword1", "keyword2", "keyword3"};
```

Another use case is a static mapping between an integer and something else, say a string (in this example french bretagne departments):

```
constexpr frozen::unordered_map<int, frozen::string, 2> = {
    {29, "finistere"_s},
    {56, "morbian"_s},
    {35, "ile-et-vilaine"_s},
    {22, "cotes d'armor"_s},
};
```
Then when given a departement number, you can quickly check if it's from bretagne and get its name.

**Comment by dkrikun** [comment]
I see, thanks!
