### ISSUE TITLE
Conan Build Integration

### ISSUE THREAD

**Issue by redi-foran** [serge-sans-paille/frozen#7]
Just a request to have the maintainer create an official [Conan](https://www.conan.io/) build package.  It's rather popular and makes using great libraries like this easier to integrate.

**Comment by serge-sans-paille** [comment]
I never did that, but from the doc that looks easy, so I'm OK with doing that kind of packaging  !

**Comment by serge-sans-paille** [comment]
Can you try https://www.conan.io/source/frozen/0.1/serge-sans-paille/testing ?

**Comment by serge-sans-paille** [comment]
(conan setup here : https://github.com/serge-sans-paille/frozen_conan)

**Comment by redi-foran** [comment]
I tried it but I think there's a bug in conan itself.  It's saying that 'serge-sans-paille' is an invalid name since it should only contain alphanumeric characters.  However, from looking at the package itself, it looks fine to me.

**Comment by serge-sans-paille** [comment]
ok, it seems to work fine on my setup, considering this closed :-)
