### ISSUE TITLE
Pre-sorting keys in constexpr unordered map

### ISSUE THREAD

**Issue by degski** [serge-sans-paille/frozen#70]
This is just a question. When constructing a constexpr unordered_map, are there any pros (or cons) of pre-sorting the keys, or is randomizing them even better (or not at all)?

**Comment by serge-sans-paille** [comment]
No :-) The real key is to provide a nice hash function!

**Comment by degski** [comment]
@serge-sans-paille Thanks for clearing that up, I can sleep better now :-D.
