### ISSUE TITLE
GCC 9.1.1 strict-overflow warnings

### ISSUE THREAD

**Issue by invexed** [serge-sans-paille/frozen#77]
GCC warns when enabling ```-Wstrict-overflow=n``` for ```n > 1```. Some of the warnings can be suppressed with ```#pragma```s, but others can't as they are triggered at the call site during ```constexpr``` expansion. 

```
[build] .../frozen-master/include/frozen/bits/pmh.h:174:8: error: assuming pointer wraparound does not occur when comparing P +- C1 with P +- C2 [-Werror=strict-overflow]
[build]   174 |   auto buckets = step_one.get_sorted_buckets();
[build]       |        ^~~~~~~
```

```
[build] .../frozen-master/include/frozen/bits/pmh.h:228:1: error: assuming pointer wraparound does not occur when comparing P +- C1 with P +- C2 [-Werror=strict-overflow]
[build]   228 | }
[build]       | ^
```

**Comment by serge-sans-paille** [comment]
Thanks for reporting! Can you share the full error log?

**Comment by invexed** [comment]
Sure, please see attached file. Thanks for the quick response.

[compilation_log.txt](https://github.com/serge-sans-paille/frozen/files/3476278/compilation_log.txt)

**Comment by invexed** [comment]
The call site is:

```cpp
constexpr auto x = frozen::unordered_map<int, int, 1>{ {0, 0} };
```

**Comment by serge-sans-paille** [comment]
Thanks! I can reproduce :-)

**Comment by serge-sans-paille** [comment]
@invexed can you confirm the patch is good on your side?

**Comment by invexed** [comment]
Sorry, I didn't get notified about the PR. Yeah I can confirm that this patch fixes things on my end. Thanks again.
