### ISSUE TITLE
could it be compatible wth c++11?  where should i modify if do that?

### ISSUE THREAD

**Issue by jamesmasika** [serge-sans-paille/frozen#84]
I'd like to use it with gcc4.8, i have to use this compiler in some reason, could you show me how i change it to be compatible wth c++11. Thanks.

**Comment by serge-sans-paille** [comment]
Unfortunately that would be a lot of work, given the limited support for constexpr in C++11. basically one would need to turn all function body into functional-style :-/

**Comment by serge-sans-paille** [comment]
That's indeed a *won't fix* ;-)
