### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by peter-moran** [serge-sans-paille/frozen#85]
Would it be possible to start tagging commits with release tags? For the sake of dependency management would be really nice to be able to specify what version I am using.

**Comment by serge-sans-paille** [comment]
Sure, I'll take advantage of that to issue something like

```
#define FROZEN_VERSION_MAJOR 1
#define FROZEN_VERSION_MINOR 0
#define FROZEN_VERSION_PATCH 0
```

would that make sense to you?

**Comment by peter-moran** [comment]
Yup! That’s how I’ve seen other libraries handle it, in addition to using git tags.

**Comment by serge-sans-paille** [comment]
see #86 for the headers, once merged I'll push the appropriate tag

**Comment by serge-sans-paille** [comment]
Tag set, thanks for triggering that!
