### ISSUE TITLE
bug in make_pmh_buckets

### ISSUE THREAD

**Issue by jibal** [serge-sans-paille/frozen#95]
>       if (bucket.size() >= result_t::bucket_max) { continue; }

This is wrong ... it needs to continue the outer `while (1)` loop, not the for loop.
(I didn't discover this in practice, just reading the code. You won't encounter the bug if you test with small numbers of keys and/or a well distributed hash function.)

**Comment by garbageslam** [comment]
thanks for reporting! I think #96 will fix this
